#!/bin/bash
# Guard the external verifier packet and private-request boundary.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

cd "${PROJECT_DIR}"

PASS=0
FAIL=0
TOTAL=0

PACKET="docs/external-verifier-packet.md"
PUBLIC_PATHS=(README.md AGENTS.md docs spec tools/verifier-kit-src)

pass() {
    PASS=$((PASS + 1))
}

fail() {
    local label="$1"
    local detail="${2:-}"
    FAIL=$((FAIL + 1))
    printf '  FAIL: %s\n' "${label}"
    if [ -n "${detail}" ]; then
        printf '%s\n' "${detail}" | sed 's/^/    /'
    fi
}

assert_contains_fixed() {
    local label="$1"
    local path="$2"
    local needle="$3"
    TOTAL=$((TOTAL + 1))

    if grep -Fq -- "${needle}" "${path}"; then
        pass
    else
        fail "${label}" "missing in ${path}: ${needle}"
    fi
}

assert_not_contains_fixed() {
    local label="$1"
    local path="$2"
    local needle="$3"
    TOTAL=$((TOTAL + 1))

    if grep -Fq -- "${needle}" "${path}"; then
        fail "${label}" "unexpected in ${path}: ${needle}"
    else
        pass
    fi
}

assert_no_public_regex() {
    local label="$1"
    local pattern="$2"
    TOTAL=$((TOTAL + 1))

    local matches rc
    set +e
    matches=$(git grep -n -i -E "${pattern}" -- "${PUBLIC_PATHS[@]}" 2>&1)
    rc=$?
    set -e

    if [ "${rc}" -eq 0 ]; then
        fail "${label}" "${matches}"
    elif [ "${rc}" -eq 1 ]; then
        pass
    else
        fail "${label}" "${matches}"
    fi
}

echo "=== External Verifier Packet Guard ==="

assert_contains_fixed "packet id present" "${PACKET}" "Packet id: \`zlar-external-verifier-packet-v0\`"
assert_contains_fixed "changelog historical wording note present" "CHANGELOG.md" "older \"pending\" language is historical, not the"
assert_contains_fixed "packet status public attestation not claimed" "${PACKET}" "Status: private verifier request sent; public attestation not claimed."
assert_contains_fixed "private request boundary explicit" "${PACKET}" "private-by-default non-Vincent verifier"
assert_contains_fixed "private request send recorded" "${PACKET}" "request was sent"
assert_contains_fixed "no completed attestation claim" "${PACKET}" "No completed external attestation is created by this packet or by sending the"
assert_contains_fixed "future sends require human naming" "${PACKET}" "until Vincent names or"
assert_contains_fixed "request boundary contract named" "${PACKET}" "Request boundary contract: \`zlar-external-verifier-request-boundary-v1\`."
assert_contains_fixed "request boundary verifier name field exact" "${PACKET}" "verifier_name:"
assert_contains_fixed "request boundary verifier organization field exact" "${PACKET}" "verifier_organization:"
assert_contains_fixed "request boundary verifier contact field exact" "${PACKET}" "verifier_contact:"
assert_contains_fixed "request boundary release under review field exact" "${PACKET}" "release_under_review:"
assert_contains_fixed "request boundary expected release tag field exact" "${PACKET}" "expected_release_tag:"
assert_contains_fixed "request boundary expected commit sha field exact" "${PACKET}" "expected_commit_sha:"
assert_contains_fixed "request boundary packet sender field exact" "${PACKET}" "packet_sender:"
assert_contains_fixed "request boundary packet sent date field exact" "${PACKET}" "packet_sent_date:"
assert_contains_fixed "request boundary closed exact wording present" "${PACKET}" "Those eight request-boundary fields are closed and exact for future contact"
assert_contains_fixed "request boundary rejects missing blank extra renamed summary moving" "${PACKET}" "Missing, blank, extra, renamed, summary-only, or moving-target"
assert_contains_fixed "request boundary rejects verifier-evidence summary collapse" "${PACKET}" "fields do not authorize contact and are not verifier evidence."
assert_contains_fixed "request boundary no attestation or public claim expansion" "${PACKET}" "public attribution, completed external attestation, production/current-machine"
assert_contains_fixed "request boundary summaries remain evolvable" "${PACKET}" "Evidence-focus summaries, version-specific release-forward commands, verifier"
assert_contains_fixed "request boundary summaries not boarding credentials" "${PACKET}" "must not be used as boarding credentials for contact or public"
assert_contains_fixed "recipient attribution private" "${PACKET}" "Recipient attribution: private by default; no public name in this repo."
assert_contains_fixed "public claim boundary present" "${PACKET}" "Public claim: no public external attestation is claimed in this repo."
assert_contains_fixed "private intake section present" "${PACKET}" "## Private Result Intake And Custody"
assert_contains_fixed "private intake is custody not publication" "${PACKET}" "Intake is a custody step, not publication."
assert_contains_fixed "custody receipt boundary present" "${PACKET}" "a private custody receipt with the claim boundary."
assert_contains_fixed "private identity not public" "${PACKET}" "identity or email in public repo material."
assert_contains_fixed "historical request preserved" "${PACKET}" "The state above is historical. Do not overwrite it"
assert_contains_fixed "prepared pinned release-forward target present" "${PACKET}" "Prepared pinned release-forward target:"
assert_contains_fixed "prepared pinned release-forward target not sent" "${PACKET}" "Status: target prepared; no new verifier request sent by this section."
assert_contains_fixed "prepared pinned release-forward tag present" "${PACKET}" "Release under review: \`v3.3.76\`."
assert_contains_fixed "prepared pinned release-forward sha present" "${PACKET}" "3369ae5f04b0735c8a11bc55c70b49c09edad0da"
assert_contains_fixed "prepared pinned backward-compatible release-forward target present" "${PACKET}" "Prepared pinned backward-compatibility release-forward target:"
assert_contains_fixed "prepared pinned backward-compatible release-forward target not sent" "${PACKET}" "Status: target prepared; no new verifier request sent by this section."
assert_contains_fixed "prepared pinned backward-compatible release-forward tag present" "${PACKET}" "Release under review: \`v3.3.90\`."
assert_contains_fixed "prepared pinned backward-compatible release-forward sha present" "${PACKET}" "9a8147163384f776777bf283217a5cd55cbbdfe7"
assert_contains_fixed "prepared pinned backward-compatible release-forward target not verifier evidence" "${PACKET}" "non-operator verifier has reviewed \`v3.3.90\`"
assert_contains_fixed "prepared pinned public-distribution release-forward target present" "${PACKET}" "Prepared pinned byte-bound public-distribution release-forward target:"
assert_contains_fixed "prepared pinned public-distribution release-forward target not sent" "${PACKET}" "Status: target prepared; no new verifier request sent by this section."
assert_contains_fixed "prepared pinned public-distribution release-forward tag present" "${PACKET}" "Release under review: \`v3.4.2\`."
assert_contains_fixed "prepared pinned public-distribution release-forward sha present" "${PACKET}" "a101282cf901c8c124b0a4761359395baad3f829"
assert_contains_fixed "prepared pinned public-distribution target readiness named" "${PACKET}" "READY_FOR_V3_4_0_PUBLIC_VERIFIER_KIT_DISTRIBUTION"
assert_contains_fixed "prepared pinned public-distribution target not verifier evidence" "${PACKET}" "verifier has reviewed \`v3.4.2\`"
assert_not_contains_fixed "packet must not label old pinned target latest completed" "${PACKET}" "latest completed release-forward target"
assert_contains_fixed "current target not verifier evidence" "${PACKET}" "It is not evidence that any"
assert_contains_fixed "release checkout command present" "${PACKET}" "git checkout v3.3.49"
assert_contains_fixed "release-forward template present" "${PACKET}" "## Release-Forward Verification Template"
assert_contains_fixed "release-forward explicit tag placeholder present" "${PACKET}" "git checkout <explicit-release-tag>"
assert_contains_fixed "release-forward exact sha check present" "${PACKET}" "test \"\$(git rev-parse HEAD)\" = \"<expected-commit-sha>\""
assert_contains_fixed "release-forward template v3.4.28 boundary present" "${PACKET}" "current \`v3.4.28+\` targets"
assert_contains_fixed "release-forward nested preflight artifact forge command present" "${PACKET}" "zlar-installed-runtime-profile-terminal-chain-forged-inner-preflight-hash-v1.json"
assert_contains_fixed "release-forward nested preflight artifact expected refusal present" "${PACKET}" "protected-records-installed-runtime-profile-terminal-chain verify --input zlar-installed-runtime-profile-terminal-chain-forged-inner-preflight-hash-v1.json # expected exit 1"
assert_contains_fixed "release-forward nested service artifact forge command present" "${PACKET}" "zlar-installed-runtime-profile-terminal-chain-forged-inner-service-hash-v1.json"
assert_contains_fixed "release-forward nested service artifact expected refusal present" "${PACKET}" "protected-records-installed-runtime-profile-terminal-chain verify --input zlar-installed-runtime-profile-terminal-chain-forged-inner-service-hash-v1.json # expected exit 1"
assert_contains_fixed "verifier environment command present" "${PACKET}" "bin/zlar verifier-env"
assert_contains_fixed "verifier environment json-out command present" "${PACKET}" "bin/zlar verifier-env --json-out zlar-verifier-env-report-v0.json"
assert_contains_fixed "verifier environment report preserved" "${PACKET}" "zlar-verifier-env-report-v0.json"
assert_contains_fixed "verifier kit build environment command present" "${PACKET}" "bash tools/build-verifier-kit.sh --check-env"
assert_contains_fixed "openssl ed25519 preflight present" "${PACKET}" "openssl genpkey -algorithm ED25519 -out /dev/null"
assert_contains_fixed "release-forward current checkout present" "${PACKET}" "git checkout v3.3.76"
assert_contains_fixed "release-forward current sha check present" "${PACKET}" "test \"\$(git rev-parse HEAD)\" = \"3369ae5f04b0735c8a11bc55c70b49c09edad0da\""
assert_contains_fixed "release-forward backward-compatible prepared checkout present" "${PACKET}" "git checkout v3.3.90"
assert_contains_fixed "release-forward backward-compatible prepared sha check present" "${PACKET}" "test \"\$(git rev-parse HEAD)\" = \"9a8147163384f776777bf283217a5cd55cbbdfe7\""
assert_contains_fixed "release-forward public-distribution prepared checkout present" "${PACKET}" "git checkout v3.4.2"
assert_contains_fixed "release-forward public-distribution prepared sha check present" "${PACKET}" "test \"\$(git rev-parse HEAD)\" = \"a101282cf901c8c124b0a4761359395baad3f829\""
assert_contains_fixed "release-forward helper command present" "${PACKET}" "bash tools/release-forward-verifier-dry-run.sh --release-tag v3.3.90 --expected-commit-sha 9a8147163384f776777bf283217a5cd55cbbdfe7"
assert_contains_fixed "release-forward helper v3.4.2 command present" "${PACKET}" "bash tools/release-forward-verifier-dry-run.sh --release-tag v3.4.2 --expected-commit-sha a101282cf901c8c124b0a4761359395baad3f829"
assert_contains_fixed "release-forward helper plan-only present" "${PACKET}" "--plan-only"
assert_contains_fixed "release-forward helper refuses moving targets" "${PACKET}" "refuses moving targets such as \`main\`, \`HEAD\`, \`latest\`, and"
assert_contains_fixed "release-forward helper preserves result file" "${PACKET}" "\`DRY-RUN-RESULT.md\`"
assert_contains_fixed "release-forward helper preserves manifest file" "${PACKET}" "\`DRY-RUN-MANIFEST.json\`"
assert_contains_fixed "release-forward helper manifest boundary present" "${PACKET}" "machine-readable result envelope"
assert_contains_fixed "release-forward helper manifest non-claim flags present" "${PACKET}" "non-claim flags"
assert_contains_fixed "release-forward helper no verifier contact boundary" "${PACKET}" "verifier, creates no public external attestation"
assert_contains_fixed "release-forward helper north star artifact present" "${PACKET}" "zlar-north-star-readiness-v1.json"
assert_contains_fixed "release-forward helper north star v3.3.98 boundary present" "${PACKET}" "For \`v3.3.98+\` targets"
assert_contains_fixed "release-forward helper north star not ready boundary present" "${PACKET}" "\`NOT_READY_FOR_V3_4_0\`"
assert_contains_fixed "release-forward helper north star no v3.4 claim present" "${PACKET}" "does not prove v3.4.0 readiness"
assert_contains_fixed "openssl failure stops packet guidance present" "${PACKET}" "preflight fails, stop and upgrade or select an OpenSSL build"
assert_contains_fixed "verifier environment failure stops packet guidance present" "${PACKET}" "If either command reports \`Result: FAIL\`, stop"
assert_contains_fixed "proof smoke command present" "${PACKET}" "bin/zlar proof-smoke"
assert_contains_fixed "proof smoke json command present" "${PACKET}" "bin/zlar proof-smoke --json > zlar-proof-smoke-v1.json"
assert_contains_fixed "proof smoke generated verification command present" "${PACKET}" "bin/zlar proof-smoke verify --input zlar-proof-smoke-v1.json --json > zlar-proof-smoke-generated-verification.json"
assert_contains_fixed "proof smoke generated verification preserved" "${PACKET}" "zlar-proof-smoke-generated-verification.json"
assert_contains_fixed "proof smoke sample verification command present" "${PACKET}" "bin/zlar proof-smoke verify --sample --json > zlar-proof-smoke-sample-verification.json"
assert_contains_fixed "local proof-pack sample verification command present" "${PACKET}" "bin/zlar local-proof-pack verify --sample --json > zlar-local-proof-pack-sample-verification.json"
assert_contains_fixed "issuer status proof json command present" "${PACKET}" "bin/zlar issuer-status-proof --json > zlar-issuer-status-proof.json"
assert_contains_fixed "verifier kit build command present" "${PACKET}" "bash tools/build-verifier-kit.sh"
assert_contains_fixed "verifier kit reproducibility command present" "${PACKET}" "bin/zlar verifier-kit-reproducibility --json-out zlar-verifier-kit-reproducibility-v1.json"
assert_contains_fixed "verifier kit public distribution release assets fixture command present" "${PACKET}" "zlar-verifier-kit-release-assets-v1.json"
assert_contains_fixed "verifier kit public distribution command present" "${PACKET}" "bin/zlar verifier-kit-public-distribution --release-tag <explicit-release-tag> --release-assets-json zlar-verifier-kit-release-assets-v1.json --reproducibility zlar-verifier-kit-reproducibility-v1.json --asset-dir . --json-out zlar-verifier-kit-public-distribution-v1.json"
assert_contains_fixed "verifier kit issuer status text command present" "${PACKET}" "( cd dist/zlar-verifier-kit-v0.1.0 && node verify-issuer-status.mjs )"
assert_contains_fixed "verifier kit recognition text command present" "${PACKET}" "( cd dist/zlar-verifier-kit-v0.1.0 && node verify-recognition.mjs --receipt examples/sample-receipt.json --registry examples/trusted-receipt-issuers-v1.json --scope verifier-kit-sample )"
assert_contains_fixed "verifier kit recognition json command present" "${PACKET}" "zlar-trusted-receipt-issuer-recognition.json"
assert_contains_fixed "verifier kit issuer status artifact command present" "${PACKET}" "( cd dist/zlar-verifier-kit-v0.1.0 && bash external-runner-dry-run.sh --issuer-status-json-out ../../zlar-verifier-kit-issuer-status-fixture.json )"
assert_contains_fixed "verifier kit external-runner diagnostics command present" "${PACKET}" "node tools/verifier-kit-external-runner-diagnostics.mjs --json-out zlar-verifier-kit-external-runner-diagnostics-v1.json"
assert_contains_fixed "verifier kit external-runner diagnostics env target present" "${PACKET}" "ZLAR_RELEASE_FORWARD_TARGET_TAG=<explicit-release-tag>"
assert_contains_fixed "verifier kit issuer status v3.3.64 boundary present" "${PACKET}" "For release targets at \`v3.3.64\` or later"
assert_contains_fixed "verifier kit issuer status v3.3.67 artifact boundary present" "${PACKET}" "For release targets at \`v3.3.67\` or later"
assert_contains_fixed "verifier kit external-runner diagnostics v3.4.21 boundary present" "${PACKET}" "For release targets at \`v3.4.21\` or later"
assert_contains_fixed "verifier kit external-runner means bundled helper" "${PACKET}" "\`external-runner\` means the bundled verifier-kit helper file"
assert_contains_fixed "verifier kit external-runner diagnostics v3.4.20 hardening present" "${PACKET}" "The report proves the \`v3.4.20\` verifier-kit"
assert_contains_fixed "verifier kit external-runner diagnostics substring boundary present" "${PACKET}" "pipefail-safe Bash substring form"
assert_contains_fixed "verifier kit external-runner diagnostics grep boundary present" "${PACKET}" "\`grep -q\`"
assert_contains_fixed "verifier kit external-runner diagnostics no tests-in-kit claim" "${PACKET}" "repo-side regression tests are not inside the built kit"
assert_contains_fixed "verifier kit recognition v3.3.94 boundary present" "${PACKET}" "For release targets at \`v3.3.94\` or later"
assert_contains_fixed "verifier kit recognition fixture boundary present" "${PACKET}" "one local registry fixture"
assert_contains_fixed "verifier kit issuer status artifact overwrite boundary present" "${PACKET}" "refuses to overwrite an existing artifact file"
assert_contains_fixed "verifier kit issuer status evidence preserved" "${PACKET}" "zlar-verifier-kit-issuer-status-fixture.json"
assert_contains_fixed "verifier kit reproducibility evidence preserved" "${PACKET}" "zlar-verifier-kit-reproducibility-v1.json"
assert_contains_fixed "verifier kit external-runner diagnostics evidence preserved" "${PACKET}" "zlar-verifier-kit-external-runner-diagnostics-v1.json"
assert_contains_fixed "verifier kit public distribution evidence preserved" "${PACKET}" "zlar-verifier-kit-public-distribution-v1.json"
assert_contains_fixed "verifier kit public distribution boundary present" "${PACKET}" "ready_for_public_distribution_claim=false"
assert_contains_fixed "verifier kit public distribution no upload boundary present" "${PACKET}" "does not upload assets"
assert_contains_fixed "verifier kit live release assets export present" "${PACKET}" "zlar-verifier-kit-release-assets-live-v1.json"
assert_contains_fixed "verifier kit live release assets helper present" "${PACKET}" "bin/zlar verifier-kit-release-assets-live-read"
assert_contains_fixed "verifier kit live release assets explicit tag present" "${PACKET}" "--release-tag v3.4.2"
assert_contains_fixed "verifier kit live release assets evidence model present" "${PACKET}" "github-release-assets-json-live-read"
assert_contains_fixed "verifier kit live release assets downloaded hash present" "${PACKET}" "downloaded SHA-256 values"
assert_contains_fixed "verifier kit live release assets download dir present" "${PACKET}" "zlar-verifier-kit-release-assets"
assert_contains_fixed "verifier kit live release assets tar extract present" "${PACKET}" "tar -xzf zlar-verifier-kit-release-assets/zlar-verifier-kit-v0.1.0.tar.gz"
assert_contains_fixed "verifier kit live require-public command present" "${PACKET}" "--require-public"
assert_contains_fixed "verifier kit live public distribution output present" "${PACKET}" "zlar-verifier-kit-public-distribution-live-v1.json"
assert_contains_fixed "verifier kit live v3.4 readiness boundary present" "${PACKET}" "This live release-asset read can support only the bounded"
assert_contains_fixed "verifier kit live v3.4 readiness result present" "${PACKET}" "READY_FOR_V3_4_0_PUBLIC_VERIFIER_KIT_DISTRIBUTION"
assert_contains_fixed "verifier kit live byte-binding boundary present" "${PACKET}" "public release-asset byte hashes match the reproducibility evidence"
assert_contains_fixed "verifier kit issuer status live non-claim present" "${PACKET}" "not prove live active issuer status"
assert_contains_fixed "attestation template verifier kit issuer status command present" "${PACKET}" "external-runner-dry-run.sh --issuer-status-json-out from the built verifier kit"
assert_contains_fixed "attestation template verifier kit recognition command present" "${PACKET}" "node verify-recognition.mjs from the built verifier kit"
assert_contains_fixed "attestation template verifier kit external-runner diagnostics command present" "${PACKET}" "node tools/verifier-kit-external-runner-diagnostics.mjs --json-out zlar-verifier-kit-external-runner-diagnostics-v1.json"
assert_contains_fixed "attestation template verifier kit external-runner diagnostics boundary present" "${PACKET}" "For v3.4.21+ targets, the verifier-kit external-runner diagnostics report is"
assert_contains_fixed "attestation template verifier kit external-runner diagnostics no attestation" "${PACKET}" "not public external attestation, not non-operator review"
assert_contains_fixed "README verifier kit external-runner diagnostics v3.4.21 guidance present" "docs/technical-reference.md" "For \`v3.4.21+\` release-forward/evaluator runs, also preserve"
assert_contains_fixed "README verifier kit external-runner diagnostics index present" "docs/technical-reference.md" "preserves \`zlar-verifier-kit-external-runner-diagnostics-v1.json\` for \`v3.4.21+\`"
assert_contains_fixed "README verifier kit external-runner diagnostics bundled helper boundary present" "docs/technical-reference.md" "\`external-runner\` means the bundled verifier-kit helper file"
assert_contains_fixed "README verifier kit external-runner diagnostics no attestation boundary present" "docs/technical-reference.md" "It is not live probing, external"
assert_contains_fixed "packet terminal chain named refusals v3.4.22 readiness present" "${PACKET}" "For \`v3.4.22+\` targets, the readiness report must also preserve"
assert_contains_fixed "packet terminal chain named refusal hash present" "${PACKET}" "\`named_receipt_refusals_sha256\`"
assert_contains_fixed "packet terminal chain manifest evidence present" "${PACKET}" "\`terminal_chain_refusal_evidence.enabled=true\`"
assert_contains_fixed "packet terminal chain result section present" "${PACKET}" "\`Terminal Chain Refusal Evidence\`"
assert_contains_fixed "packet terminal chain recognition groups v3.4.23 readiness present" "${PACKET}" "For \`v3.4.23+\` targets, the readiness report must also preserve"
assert_contains_fixed "packet terminal chain recognition groups required present" "${PACKET}" "\`installed_runtime_profile_terminal_chain_recognition_refusal_groups_required=true\`"
assert_contains_fixed "packet terminal chain recognition groups preserved present" "${PACKET}" "\`installed_runtime_profile_terminal_chain_recognition_refusal_groups_preserved=true\`"
assert_contains_fixed "packet terminal chain recognition groups hash present" "${PACKET}" "\`recognition_refusal_groups_sha256\`"
assert_contains_fixed "packet terminal chain recognition case ids v3.4.24 manifest present" "${PACKET}" "For \`v3.4.24+\` targets, the release-forward manifest must also report"
assert_contains_fixed "packet terminal chain recognition case ids required present" "${PACKET}" "\`recognition_refusal_group_case_ids_required=true\`"
assert_contains_fixed "packet terminal chain recognition case ids preserved present" "${PACKET}" "\`all_recognition_refusal_group_case_ids_preserved=true\`"
assert_contains_fixed "packet terminal chain recognition case ids result present" "${PACKET}" "must print the exact case-id lists"
assert_contains_fixed "packet terminal chain recognition case IDs v3.4.25 report contract present" "${PACKET}" "For \`v3.4.25+\` targets, proof-smoke and North Star readiness must also preserve"
assert_contains_fixed "packet terminal chain recognition case IDs v3.4.25 counts present" "${PACKET}" "\`group_count=3\`, \`case_count=18\`, and exact grouped case IDs"
assert_contains_fixed "packet terminal chain recognition case IDs v3.4.26 observed summaries present" "${PACKET}" "For \`v3.4.26+\` targets, the North Star readiness Enterprise Deployment Profile"
assert_contains_fixed "packet terminal chain nested artifact binding v3.4.28 present" "${PACKET}" "For \`v3.4.28+\` targets, terminal-chain evidence and its portable artifact must"
assert_contains_fixed "packet terminal chain recognition case IDs v3.4.25 result section present" "${PACKET}" "\`Release-Forward Report Contract\`"
assert_contains_fixed "packet terminal chain recognition groups manifest present" "${PACKET}" "\`recognition_refusal_groups_required=true\`"
assert_contains_fixed "packet terminal chain recognition groups before mutation present" "${PACKET}" "route/request-authority refusals marked before mutation"
assert_contains_fixed "packet terminal chain recognition case ids checklist present" "${PACKET}" "For v3.4.24+ targets, also confirm that section contains"
assert_contains_fixed "packet terminal chain recognition case ids v3.4.25 checklist present" "${PACKET}" "For v3.4.25+ targets, also confirm \`DRY-RUN-RESULT.md\` contains"
assert_contains_fixed "packet terminal chain recognition case ids v3.4.25 north star required present" "${PACKET}" "\`north_star.counts.installed_runtime_profile_terminal_chain_recognition_refusal_group_case_ids_required=true\`"
assert_contains_fixed "packet terminal chain recognition case ids v3.4.25 proof-smoke count present" "${PACKET}" "\`proof_smoke.counts.installed_runtime_profile_terminal_chain_recognition_refusal_group_count=3\`"
assert_contains_fixed "packet terminal chain recognition case ids v3.4.26 checklist present" "${PACKET}" "For v3.4.26+ targets, also confirm \`DRY-RUN-RESULT.md\` contains"
assert_contains_fixed "packet terminal chain recognition case ids v3.4.26 puzzle 3 present" "${PACKET}" "\`north_star.puzzle_3.observed.installed_runtime_profile_terminal_chain_recognition_refusal_group_case_ids_preserved=true\`"
assert_contains_fixed "packet terminal chain recognition case ids v3.4.26 puzzle 5 present" "${PACKET}" "\`north_star.puzzle_5.observed.installed_runtime_profile_terminal_chain_recognition_refusal_group_case_count=18\`"
assert_contains_fixed "packet private intake content binding v3.4.47 present" "${PACKET}" "For v3.4.47+ targets, also confirm \`DRY-RUN-RESULT.md\` prints"
assert_contains_fixed "packet private intake content binding verified present" "${PACKET}" "\`private_result_verification.evidence_dir_contract_verified=true\`"
assert_contains_fixed "packet private intake content binding type present" "${PACKET}" "\`private_result_verification.evidence_dir_contract_type=product-proof-path-terminal-chain-recognition-refusal-group-case-ids-v1\`"
assert_contains_fixed "packet private intake content binding count present" "${PACKET}" "\`private_result_verification.terminal_chain_recognition_refusal_group_case_count=18\`"
assert_contains_fixed "packet deployment bridge v3.4.48 product proof path present" "${PACKET}" "For \`v3.4.48+\` targets, also confirm"
assert_contains_fixed "packet deployment bridge product proof path gate present" "${PACKET}" "\`acceptance_gate.deployment_profile_authority_bridge_observed=true\`"
assert_contains_fixed "packet deployment bridge release-forward contract present" "${PACKET}" "For \`v3.4.48+\` targets, that contract must also carry the Product Proof Path"
assert_contains_fixed "packet deployment bridge private intake validator present" "${PACKET}" "For \`v3.4.48+\`, the same verification also validates the Product Proof Path"
assert_contains_fixed "packet deployment bridge private intake contract type present" "${PACKET}" "\`private_result_verification.evidence_dir_contract_type=product-proof-path-terminal-chain-and-deployment-profile-authority-bridge-v1\`"
assert_contains_fixed "packet deployment bridge private intake preserved present" "${PACKET}" "\`private_result_verification.deployment_profile_authority_bridge_preserved=true\`"
assert_contains_fixed "packet v3.4.51 private intake contract type present" "${PACKET}" "\`private_result_verification.evidence_dir_contract_type=product-proof-path-terminal-chain-deployment-profile-authority-refusals-trusted-registry-verdict-and-downstream-refusal-boundary-v1\`"
assert_contains_fixed "packet v3.4.51 private intake downstream unboarded present" "${PACKET}" "\`private_result_verification.downstream_refusal_all_refusals_unboarded=true\`"
assert_contains_fixed "packet v3.4.51 private intake downstream reasons present" "${PACKET}" "\`private_result_verification.downstream_refusal_reasons=receipt_missing,receipt_invalid,issuer_not_active,unknown_issuer,outcome_not_boarding,policy_not_recognized,domain_out_of_scope,tool_out_of_scope,audit_event_mismatch,detail_hash_mismatch,receipt_stale\`"
assert_contains_fixed "packet v3.4.51 private intake north-star downstream unboarded present" "${PACKET}" "\`private_result_verification.north_star_downstream_refusal_all_refusals_unboarded=true\`"
assert_contains_fixed "packet v3.4.51 private intake north-star downstream reasons present" "${PACKET}" "\`private_result_verification.north_star_downstream_refusal_reasons=receipt_missing,receipt_invalid,issuer_not_active,unknown_issuer,outcome_not_boarding,policy_not_recognized,domain_out_of_scope,tool_out_of_scope,audit_event_mismatch,detail_hash_mismatch,receipt_stale\`"
assert_contains_fixed "packet north star private verifier downstream summary present" "${PACKET}" "When a private verifier-result verification JSON is supplied to North Star"
assert_contains_fixed "packet north star private verifier downstream reasons present" "${PACKET}" "the exact \`north_star_downstream_refusal_reasons\`"
assert_contains_fixed "packet private intake v3.4.51 downstream identity prose present" "${PACKET}" "manifest Product Proof Path contract and North Star mirror, including exact"
assert_contains_fixed "packet private intake content binding nonclaim present" "${PACKET}" "This is private-intake content binding only"
assert_contains_fixed "packet terminal chain nested artifact binding v3.4.28 checklist present" "${PACKET}" "For v3.4.28+ targets, also confirm \`DRY-RUN-RESULT.md\` contains"
assert_contains_fixed "packet terminal chain nested artifact tamper preflight result present" "${PACKET}" "\`release_forward.terminal_chain_nested_artifact_tamper_refusals.generated_preflight_artifact_type=zlar-protected-records-installed-runtime-profile-preflight-artifact-v1\`"
assert_contains_fixed "packet terminal chain nested artifact tamper preflight refusal result present" "${PACKET}" "\`release_forward.terminal_chain_nested_artifact_tamper_refusals.forged_inner_preflight_hash_refused=true\`"
assert_contains_fixed "packet terminal chain nested artifact tamper refusal result present" "${PACKET}" "\`release_forward.terminal_chain_nested_artifact_tamper_refusals.forged_inner_service_hash_refused=true\`"
assert_contains_fixed "packet terminal chain nested artifact binding v3.4.30 checklist present" "${PACKET}" "For v3.4.30+ targets, also confirm \`DRY-RUN-RESULT.md\` contains"
assert_contains_fixed "packet terminal chain nested artifact binding preflight hash present" "${PACKET}" "\`release_forward.terminal_chain_nested_artifact_binding.generated_preflight_artifact_body_sha256=\`"
assert_contains_fixed "packet terminal chain nested artifact binding service hash bound present" "${PACKET}" "\`release_forward.terminal_chain_nested_artifact_binding.service_artifact_hash_bound=true\`"
assert_contains_fixed "packet release asset repository binding present" "${PACKET}" "verifier-kit release-asset live-read"
assert_contains_fixed "packet release asset repository binding names ZLAR" "${PACKET}" "repository \`ZLAR-AI/ZLAR\`"
assert_contains_fixed "packet release asset incomplete live not ready present" "${PACKET}" "release-asset evidence remains bounded \`NOT_READY\` evidence"
assert_contains_fixed "packet trusted issuer registry evidence v3.4.35 present" "${PACKET}" "For v3.4.35+ targets, also confirm \`DRY-RUN-MANIFEST.json\` contains"
assert_contains_fixed "packet trusted issuer registry evidence enabled present" "${PACKET}" "\`trusted_issuer_registry_recognition_evidence.enabled=true\`"
assert_contains_fixed "packet trusted issuer registry evidence result section present" "${PACKET}" "\`Trusted Issuer Registry Recognition Evidence\`"
assert_contains_fixed "README terminal chain named refusals present" "docs/technical-reference.md" "preserves terminal-chain named refusal evidence for \`v3.4.22+\`"
assert_contains_fixed "README terminal chain recognition groups present" "docs/technical-reference.md" "preserves terminal-chain recognition refusal groups for \`v3.4.23+\`"
assert_contains_fixed "README terminal chain recognition case ids present" "docs/technical-reference.md" "requires exact terminal-chain recognition-refusal group case IDs in the manifest for \`v3.4.24+\`"
assert_contains_fixed "README terminal chain recognition case ids v3.4.25 present" "docs/technical-reference.md" "requires proof-smoke and North Star readiness to preserve those same exact grouped case IDs for \`v3.4.25+\`"
assert_contains_fixed "README terminal chain recognition case ids v3.4.26 present" "docs/technical-reference.md" "requires North Star readiness observed summaries to mirror that case-ID contract for \`v3.4.26+\`"
assert_contains_fixed "README private intake content binding v3.4.47 present" "docs/technical-reference.md" "For \`v3.4.47+\`, private result verification over an evidence directory also"
assert_contains_fixed "README private intake v3.4.51 downstream reasons present" "docs/technical-reference.md" "including exact downstream refusal reasons and"
assert_contains_fixed "README private intake v3.4.51 downstream unboarded present" "docs/technical-reference.md" "all-refusals-unboarded flags"
assert_contains_fixed "README private intake content binding no attestation present" "docs/technical-reference.md" "private/internal intake only, not public external attestation"
assert_contains_fixed "README terminal chain nested artifact tamper v3.4.28 present" "docs/technical-reference.md" "requires terminal-chain nested artifacts and forged inner preflight/service-proof hash refusals for \`v3.4.28+\`"
assert_contains_fixed "README terminal chain nested artifact binding v3.4.30 present" "docs/technical-reference.md" "requires verifier-owned terminal-chain nested artifact binding summaries for \`v3.4.30+\`"
assert_contains_fixed "README release asset exact target boundary present" "docs/technical-reference.md" "keeps public-ready verifier-kit release-asset evidence tied to the exact asset-bearing target"
assert_contains_fixed "README trusted issuer registry evidence v3.4.35 present" "docs/technical-reference.md" "requires first-class trusted-issuer registry recognition evidence in the manifest and result for \`v3.4.35+\`"
assert_contains_fixed "README trusted issuer registry result present" "docs/technical-reference.md" "for \`v3.4.35+\` it prints trusted-issuer registry recognition verdict"
assert_contains_fixed "README terminal chain nested artifact tamper result present" "docs/technical-reference.md" "for \`v3.4.28+\` it prints terminal-chain nested artifact tamper refusals"
assert_contains_fixed "README terminal chain nested artifact binding result present" "docs/technical-reference.md" "for \`v3.4.30+\` it prints verifier-owned nested artifact binding body hashes and binding booleans"
assert_contains_fixed "README terminal chain manifest evidence present" "docs/technical-reference.md" "\`terminal_chain_refusal_evidence\` section with named receipt-refusal preservation"
assert_contains_fixed "README terminal chain recognition groups manifest present" "docs/technical-reference.md" "for \`v3.4.23+\` grouped recognition-refusal preservation"
assert_contains_fixed "README terminal chain recognition case ids manifest present" "docs/technical-reference.md" "for \`v3.4.24+\` exact grouped recognition-refusal case-ID preservation"
assert_contains_fixed "README terminal chain recognition case ids report contract present" "docs/technical-reference.md" "for \`v3.4.25+\` proof-smoke/readiness report-contract preservation"
assert_contains_fixed "README terminal chain recognition case ids observed summaries present" "docs/technical-reference.md" "for \`v3.4.26+\` observed-summary preservation"
assert_contains_fixed "CLI reference terminal chain recognition groups command docs present" "docs/cli-reference.md" "canonical \`recognition_refusal_groups\`"
assert_contains_fixed "CLI reference release asset repository binding present" "docs/cli-reference.md" "repository \`ZLAR-AI/ZLAR\`"
assert_contains_fixed "CLI reference incomplete live not ready present" "docs/cli-reference.md" "Incomplete live evidence remains bounded"
assert_contains_fixed "CLI reference trusted issuer registry evidence v3.4.35 present" "docs/cli-reference.md" "For \`v3.4.35+\` targets, release-forward evidence also presents the existing"
assert_contains_fixed "CLI reference trusted issuer registry evidence field present" "docs/cli-reference.md" "\`trusted_issuer_registry_recognition_evidence\`"
assert_contains_fixed "CLI reference trusted issuer registry evidence result present" "docs/cli-reference.md" "\`Trusted Issuer Registry Recognition Evidence\`"
assert_contains_fixed "CLI reference terminal chain recognition case IDs command docs present" "docs/cli-reference.md" "stable \`case_count\` and \`cases[].case_id\`"
assert_contains_fixed "CLI reference terminal chain recognition groups v3.4.23 readiness present" "docs/cli-reference.md" "For \`v3.4.23+\` release-forward evidence"
assert_contains_fixed "CLI reference terminal chain recognition groups required count present" "docs/cli-reference.md" "\`installed_runtime_profile_terminal_chain_recognition_refusal_groups_required=true\`"
assert_contains_fixed "CLI reference terminal chain recognition case IDs v3.4.24 present" "docs/cli-reference.md" "release-forward verifier packet for \`v3.4.24+\` additionally requires"
assert_contains_fixed "CLI reference terminal chain recognition case IDs v3.4.25 present" "docs/cli-reference.md" "release-forward readiness contract for \`v3.4.25+\` additionally requires"
assert_contains_fixed "CLI reference terminal chain recognition case IDs v3.4.25 proof-smoke present" "docs/cli-reference.md" "For \`v3.4.25+\`, the report counts also preserve exact terminal-chain"
assert_contains_fixed "CLI reference terminal chain recognition case IDs v3.4.26 present" "docs/cli-reference.md" "For \`v3.4.26+\`, the North Star readiness Enterprise Deployment Profile"
assert_contains_fixed "CLI reference private intake content binding v3.4.47 present" "docs/cli-reference.md" "For \`v3.4.47+\`, private result verification with \`--evidence-dir\` also validates"
assert_contains_fixed "CLI reference private intake content binding manifest present" "docs/cli-reference.md" "Product Proof Path content contract from \`DRY-RUN-MANIFEST.json\`"
assert_contains_fixed "CLI reference private intake downstream reasons present" "docs/cli-reference.md" "\`downstream_refusal_reasons\`"
assert_contains_fixed "CLI reference private intake north-star downstream reasons present" "docs/cli-reference.md" "\`north_star_downstream_refusal_reasons\`"
assert_contains_fixed "CLI reference terminal-chain v3.4.51 downstream identity present" "docs/cli-reference.md" "all-refusals-unboarded flags; this remains local fixture"
assert_contains_fixed "CLI reference stale-or-expired named refusal present" "docs/cli-reference.md" "\`stale_or_expired\`, unknown-issuer"
assert_contains_fixed "CLI reference stale-or-expired receipt-stale backing present" "docs/cli-reference.md" "backed by the stable"
assert_contains_fixed "CLI reference stale-or-expired no receipt-expired contract present" "docs/cli-reference.md" "not a separate \`receipt_expired\` contract"
assert_contains_fixed "CLI reference north star private verifier summary present" "docs/cli-reference.md" "When a private verifier-result verification JSON is supplied"
assert_contains_fixed "CLI reference terminal chain nested artifact command docs present" "docs/cli-reference.md" "service-proof artifacts in \`nested_artifacts\`"
assert_contains_fixed "CLI reference terminal chain nested artifact v3.4.28 present" "docs/cli-reference.md" "release-forward readiness contract for \`v3.4.28+\` additionally requires"
assert_contains_fixed "active profile v3.3.76 boundary present" "${PACKET}" "For release targets at \`v3.3.76\` or later"
assert_contains_fixed "active profile selection verified count preserved" "${PACKET}" "active_profile_selection_verified=true"
assert_contains_fixed "active profile no latest count preserved" "${PACKET}" "active_profile_selects_latest=false"
assert_contains_fixed "active profile no live runtime profile count preserved" "${PACKET}" "active_profile_live_runtime_profile_checked=false"
assert_contains_fixed "active profile no persistent runtime profile count preserved" "${PACKET}" "active_profile_persistent_runtime_profile_installed=false"
assert_contains_fixed "active profile embedded summary preserved" "${PACKET}" "\`active_profile_selection\` summary"
assert_contains_fixed "active profile fixture scope preserved" "${PACKET}" "selection_scope=local-disposable-proof-harness"
assert_contains_fixed "active profile persistent install non-claim present" "${PACKET}" "persistent runtime profile"
assert_contains_fixed "README active profile count guidance present" "docs/technical-reference.md" "For \`v3.3.76+\` evaluator runs, preserve the smoke counts"
assert_contains_fixed "README active profile fixture non-claim present" "docs/technical-reference.md" "fixture-contained selection evidence only; it is not persistent runtime profile"
assert_contains_fixed "coverage map active profile count guidance present" "docs/governed-surface-coverage-map.md" "For \`v3.3.76+\` reviews, preserve the smoke active-profile counts"
assert_contains_fixed "coverage map active profile no persistent count present" "docs/governed-surface-coverage-map.md" "active_profile_persistent_runtime_profile_installed=false"
assert_contains_fixed "attestation template active profile preservation prompt present" "${PACKET}" "For v3.3.76+ targets, active-profile counts and the embedded proof-pack"
assert_contains_fixed "runtime profile installation v3.3.81 boundary present" "${PACKET}" "For release targets at \`v3.3.81\` or later"
assert_contains_fixed "runtime profile installation applied count preserved" "${PACKET}" "runtime_profile_installation_applied=true"
assert_contains_fixed "runtime profile installation authority guard count preserved" "${PACKET}" "runtime_profile_installation_request_authority_guard_refused=true"
assert_contains_fixed "runtime profile installation no latest count preserved" "${PACKET}" "runtime_profile_installation_selects_latest=false"
assert_contains_fixed "runtime profile installation no persistent count preserved" "${PACKET}" "runtime_profile_installation_persistent_profile_installed=false"
assert_contains_fixed "runtime profile installation no hook count preserved" "${PACKET}" "runtime_profile_installation_hook_configuration_written=false"
assert_contains_fixed "runtime profile installation embedded summary preserved" "${PACKET}" "\`runtime_profile_installation\` summary"
assert_contains_fixed "runtime profile installation sample verification command present" "${PACKET}" "bin/zlar protected-records-runtime-profile-installation verify --sample --json > zlar-runtime-profile-installation-sample-verification.json"
assert_contains_fixed "runtime profile installation evidence preserved" "${PACKET}" "zlar-runtime-profile-installation-sample-verification.json"
assert_contains_fixed "runtime profile installation attestation template prompt present" "${PACKET}" "For v3.3.81+ targets, runtime-profile installation counts and the embedded"
assert_contains_fixed "installed runtime profile preflight v3.4.5 boundary present" "${PACKET}" "For release targets at \`v3.4.5\` or later"
assert_contains_fixed "installed runtime profile preflight command present" "${PACKET}" "bin/zlar protected-records-installed-runtime-profile-preflight verify --sample --json > zlar-installed-runtime-profile-preflight-sample-verification.json"
assert_contains_fixed "installed runtime profile preflight evidence preserved" "${PACKET}" "zlar-installed-runtime-profile-preflight-sample-verification.json"
assert_contains_fixed "installed runtime profile preflight read-only count preserved" "${PACKET}" "installed_runtime_profile_preflight_read_only=true"
assert_contains_fixed "installed runtime profile preflight no latest count preserved" "${PACKET}" "installed_runtime_profile_preflight_selects_latest=false"
assert_contains_fixed "installed runtime profile preflight no activation count preserved" "${PACKET}" "installed_runtime_profile_preflight_activation_performed=false"
assert_contains_fixed "installed runtime profile preflight no downstream count preserved" "${PACKET}" "installed_runtime_profile_preflight_downstream_refusal_proven=false"
assert_contains_fixed "installed runtime profile preflight no current-machine count preserved" "${PACKET}" "installed_runtime_profile_preflight_current_machine_governance_proven=false"
assert_contains_fixed "installed runtime profile preflight non-claim present" "${PACKET}" "selector-integrity preflight evidence only"
assert_contains_fixed "installed runtime profile recognition v3.4.6 boundary present" "${PACKET}" "For release targets at \`v3.4.6\` or later"
assert_contains_fixed "installed runtime profile recognition count preserved" "${PACKET}" "installed_runtime_profile_preflight_recognition_contract_preserved=true"
assert_contains_fixed "installed runtime profile recognition non-claim present" "${PACKET}" "does not prove production downstream recognition"
assert_contains_fixed "installed runtime profile recognition proof command present" "${PACKET}" "bin/zlar protected-records-installed-runtime-profile-recognition-proof --sample --json > zlar-installed-runtime-profile-recognition-proof-v1.json"
assert_contains_fixed "installed runtime profile recognition proof evidence preserved" "${PACKET}" "zlar-installed-runtime-profile-recognition-proof-v1.json"
assert_contains_fixed "installed runtime profile recognition proof v3.4.7 boundary present" "${PACKET}" "For release targets at \`v3.4.7\` or later"
assert_contains_fixed "installed runtime profile recognition proof artifact command present" "${PACKET}" "bin/zlar protected-records-installed-runtime-profile-recognition-proof --sample --artifact zlar-installed-runtime-profile-recognition-proof-artifact-v1.json"
assert_contains_fixed "installed runtime profile recognition proof artifact verify command present" "${PACKET}" "bin/zlar protected-records-installed-runtime-profile-recognition-proof verify --input zlar-installed-runtime-profile-recognition-proof-artifact-v1.json --json > zlar-installed-runtime-profile-recognition-proof-artifact-verification-v1.json"
assert_contains_fixed "installed runtime profile recognition proof artifact evidence preserved" "${PACKET}" "zlar-installed-runtime-profile-recognition-proof-artifact-v1.json"
assert_contains_fixed "installed runtime profile recognition proof artifact verification preserved" "${PACKET}" "zlar-installed-runtime-profile-recognition-proof-artifact-verification-v1.json"
assert_contains_fixed "installed runtime profile recognition proof artifact v3.4.8 boundary present" "${PACKET}" "For release targets at \`v3.4.8\` or later"
assert_contains_fixed "product proof path command present" "${PACKET}" "bin/zlar product-proof-path --json-out zlar-product-proof-path-v1.json"
assert_contains_fixed "product proof path evidence preserved" "${PACKET}" "zlar-product-proof-path-v1.json"
assert_contains_fixed "product proof path v3.4.9 boundary present" "${PACKET}" "For release targets at \`v3.4.9\` or later"
assert_contains_fixed "product proof path report type preserved" "${PACKET}" "report_type=zlar-product-proof-path-v1"
assert_contains_fixed "product proof path fixture model preserved" "${PACKET}" "evidence_model=fresh-local-fixture-proof-pack"
assert_contains_fixed "product proof path acceptance gate boundary present" "${PACKET}" "all acceptance gates true"
assert_contains_fixed "product proof path forbidden flags boundary present" "${PACKET}" "all forbidden-claim flags false"
assert_contains_fixed "product proof path all mcp non-claim present" "${PACKET}" "all-MCP governance"
assert_contains_fixed "installed runtime profile recognition proof verified count preserved" "${PACKET}" "installed_runtime_profile_recognition_proof_verified=true"
assert_contains_fixed "installed runtime profile recognition proof refusal count preserved" "${PACKET}" "installed_runtime_profile_recognition_refusal_case_count=18"
assert_contains_fixed "installed runtime profile recognition proof no service count preserved" "${PACKET}" "installed_runtime_profile_recognition_runtime_service_started=false"
assert_contains_fixed "installed runtime profile recognition proof no current-machine count preserved" "${PACKET}" "installed_runtime_profile_recognition_current_machine_governance_proven=false"
assert_contains_fixed "runtime refusal taxonomy v3.3.90 boundary present" "${PACKET}" "For release targets at \`v3.3.90\` or later"
assert_contains_fixed "runtime refusal taxonomy local activation evidence named" "${PACKET}" "zlar-runtime-local-activation-sample-verification.json"
assert_contains_fixed "runtime refusal taxonomy installation evidence named" "${PACKET}" "zlar-runtime-profile-installation-sample-verification.json"
assert_contains_fixed "runtime refusal taxonomy wrong audit event preserved" "${PACKET}" "wrong_audit_event_refused=true"
assert_contains_fixed "runtime refusal taxonomy wrong runtime profile id preserved" "${PACKET}" "wrong_runtime_profile_id_refused=true"
assert_contains_fixed "runtime refusal taxonomy agent supplied authority preserved" "${PACKET}" "agent_supplied_authority_material_refused=true"
assert_contains_fixed "runtime refusal taxonomy non-claim present" "${PACKET}" "committed local disposable runtime/profile-installation samples"
assert_contains_fixed "historical service profile coverage v3.3.91 boundary present" "${PACKET}" 'Historical pinned-release contract only: for release targets at `v3.3.91` or'
assert_contains_fixed "historical service profile coverage governed count preserved" "${PACKET}" "governed_lanes=6"
assert_contains_fixed "historical service profile coverage counted count preserved" "${PACKET}" "counted_lanes=6"
assert_contains_fixed "current checkout coverage demotion present" "${PACKET}" 'Current checkout note: its static coverage result is `4/6`, not `6/6`.'
assert_contains_fixed "current checkout exhausted grant boundary present" "${PACKET}" 'under the exhausted grant.'
assert_contains_fixed "historical six of six not projected forward" "${PACKET}" 'historical for the named release targets and must not be projected forward.'
assert_contains_fixed "service profile coverage lane preserved" "${PACKET}" "protected-records.service-profile.records.write"
assert_contains_fixed "service profile coverage runtime boundary preserved" "${PACKET}" "runtime_profile_not_installed"
assert_contains_fixed "service profile coverage wrong-policy refusal preserved" "${PACKET}" "wrong_policy_refused=true"
assert_contains_fixed "service profile coverage wrong-policy reason preserved" "${PACKET}" "wrong_policy_reason=policy_not_recognized"
assert_contains_fixed "service profile coverage wrong-policy state delta preserved" "${PACKET}" "wrong_policy_state_delta=0"
assert_contains_fixed "service profile coverage non-claim present" "${PACKET}" "committed local disposable service-profile preflight artifact"
assert_contains_fixed "README runtime profile installation count guidance present" "docs/technical-reference.md" "For \`v3.3.81+\` evaluator runs, also preserve the disposable installed-profile"
assert_contains_fixed "coverage map runtime profile installation count guidance present" "docs/governed-surface-coverage-map.md" "For \`v3.3.81+\` reviews, also preserve the disposable installed-profile counts"
assert_contains_fixed "coverage map service profile count guidance present" "docs/governed-surface-coverage-map.md" "For \`v3.3.91+\` reviews, also preserve the service-profile coverage lane"
assert_contains_fixed "coverage map v3.4.51 downstream boundary guidance present" "docs/governed-surface-coverage-map.md" "downstream-refusal marker boundary in both the"
assert_contains_fixed "coverage map v3.4.51 downstream reasons guidance present" "docs/governed-surface-coverage-map.md" "including exact downstream"
assert_contains_fixed "cli reference v3.4.51 downstream unboarded guidance present" "docs/cli-reference.md" "all-refusals-unboarded flags"
assert_contains_fixed "verifier kit runner external attestation boundary present" "tools/verifier-kit-src/EXTERNAL-RUNNER.md" "No external attestation is claimed for this run unless a real non-operator runner"
assert_contains_fixed "verifier kit result template external attestation boundary present" "tools/verifier-kit-src/EXTERNAL-RUNNER-RESULT-TEMPLATE.md" "No external attestation is claimed for this run unless a real non-operator runner"
assert_contains_fixed "verifier environment output preserved" "${PACKET}" "\`bin/zlar verifier-env\` output"
assert_contains_fixed "verifier environment failure report section present" "${PACKET}" "## Verifier Environment Failure Report v0"
assert_contains_fixed "verifier environment failure schema named" "${PACKET}" "zlar-verifier-env-failure-report-v0"
assert_contains_fixed "verifier environment failure checksum named" "${PACKET}" "zlar-verifier-env-failure-report-v0.sha256"
assert_contains_fixed "verifier environment failure evidence only" "${PACKET}" "failure evidence only"
assert_contains_fixed "verifier environment failure private by default" "${PACKET}" "private by default"
assert_contains_fixed "verifier environment failure not public attestation" "${PACKET}" "not a public"
assert_contains_fixed "verifier environment failure not key custody" "${PACKET}" "not key custody"
assert_contains_fixed "verifier environment failure not live issuer status" "${PACKET}" "not live issuer-status"
assert_contains_fixed "verifier environment failure not production authority" "${PACKET}" "not production authority"
assert_contains_fixed "verifier environment failure prerequisite wording" "${PACKET}" "verifier environment prerequisite failure"
assert_contains_fixed "verifier environment privacy exclusions" "${PACKET}" "raw \`PATH\`, private"
assert_contains_fixed "verifier kit build environment output preserved" "${PACKET}" "\`bash tools/build-verifier-kit.sh --check-env\` output"
assert_contains_fixed "runtime local activation sample verification command present" "${PACKET}" "bin/zlar protected-records-runtime-local-activation verify --sample --json > zlar-runtime-local-activation-sample-verification.json"
assert_contains_fixed "coverage sample command present" "${PACKET}" "bin/zlar coverage --sample --require-governed"
assert_contains_fixed "coverage sample json command present" "${PACKET}" "bin/zlar coverage --sample --require-governed --json > zlar-coverage-map-sample.json"
assert_contains_fixed "north star readiness command present" "${PACKET}" "bin/zlar north-star-readiness --evidence-dir . --release-tag <explicit-release-tag> --json > zlar-north-star-readiness-v1.json"
assert_contains_fixed "north star readiness evidence preserved" "${PACKET}" "\`zlar-north-star-readiness-v1.json\`, when reviewing a \`v3.3.98+\`"
assert_contains_fixed "verifier kit reproducibility v3.3.100 evidence preserved" "${PACKET}" "\`zlar-verifier-kit-reproducibility-v1.json\`, when reviewing a \`v3.3.100+\`"
assert_contains_fixed "verifier kit public distribution v3.3.109 evidence preserved" "${PACKET}" "\`zlar-verifier-kit-public-distribution-v1.json\`, when reviewing a"
assert_contains_fixed "north star readiness release target boundary present" "${PACKET}" "For release targets at \`v3.3.98\` or later"
assert_contains_fixed "north star readiness result preserved" "${PACKET}" "\`result=NOT_READY_FOR_V3_4_0\`"
assert_contains_fixed "north star readiness current machine false preserved" "${PACKET}" "\`current_machine_governance=false\`"
assert_contains_fixed "north star readiness live mcp false preserved" "${PACKET}" "\`live_mcp_coverage=false\`"
assert_contains_fixed "north star readiness unrouted false preserved" "${PACKET}" "\`unrouted_surface_coverage=false\`"
assert_contains_fixed "north star readiness consumes verifier reproducibility" "${PACKET}" "\`verifier_kit_reproducibility.provided=true\`"
assert_contains_fixed "north star readiness verifier reproducibility boundary false" "${PACKET}" "false claim-boundary flags"
assert_contains_fixed "north star readiness verifier reproducibility report named" "${PACKET}" "verifier-kit reproducibility report"
assert_contains_fixed "north star readiness consumes verifier public distribution" "${PACKET}" "\`verifier_kit_public_distribution.provided=true\`"
assert_contains_fixed "north star readiness verifier public distribution not ready" "${PACKET}" "\`ready_for_public_distribution_claim=false\`"
assert_contains_fixed "north star readiness private intake pointer named" "${PACKET}" "\`private_verifier_result_sample\` manifest pointer contract"
assert_contains_fixed "north star readiness private intake pointer boundary" "${PACKET}" "not public external attestation"
assert_contains_fixed "north star readiness attestation template command present" "${PACKET}" "- bin/zlar north-star-readiness --evidence-dir . --release-tag <explicit-release-tag> --json"
assert_contains_fixed "north star readiness attestation prompt present" "${PACKET}" "For v3.3.98+ targets, the North Star readiness report is preserved"
assert_contains_fixed "verifier kit reproducibility attestation prompt present" "${PACKET}" "For v3.3.100+ targets, the verifier-kit reproducibility report is preserved"
assert_contains_fixed "verifier kit public distribution attestation prompt present" "${PACKET}" "For v3.3.109+ targets, the verifier-kit public distribution posture report is"
assert_contains_fixed "coverage summary field named" "${PACKET}" "coverage_summary"
assert_contains_fixed "last decision field named" "${PACKET}" "last_decision"
assert_contains_fixed "last receipt field named" "${PACKET}" "last_receipt"
assert_contains_fixed "issuer identity field named" "${PACKET}" "issuer_identity"
assert_contains_fixed "known boundaries field named" "${PACKET}" "known_boundaries"
assert_contains_fixed "receipt authority guard command present" "${PACKET}" "bash tests/test-receipt-authority-copy.sh"
assert_contains_fixed "attestation template limits production" "${PACKET}" "It does not attest production deployment, live/current-machine governance,"
assert_contains_fixed "public truthful claim present" "${PACKET}" "No public external attestation is claimed in this"
assert_contains_fixed "README links packet" "docs/technical-reference.md" "External verifiers"

assert_no_public_regex \
    "public docs must not claim completed external attestation" \
    '(^|[^[:alnum:]_])(external attestation (is )?(complete|completed|done|achieved)|ZLAR is externally attested|externally attested ZLAR|non[- ]Vincent verifier (has )?(verified|attested)|independently attested by)'

assert_no_public_regex \
    "public docs must not preserve stale pre-contact verifier state" \
    '(^|[^[:alnum:]_])(This is a no-contact packet|Status:[[:space:]]*prepared/pending|no verifier has been contacted|contacted or appointed|prepared[[:space:]]+only|prepared/pending unless)'

assert_no_public_regex \
    "public docs must not preserve stale attestation-pending verifier state" \
    '(^|[^[:alnum:]_])(Status:[[:space:]]*private verifier request sent; attestation pending|no completed attestation has been received)'

assert_no_public_regex \
    "public docs must not use pending-shaped external attestation phrasing" \
    'Not externally attested yet'

assert_no_public_regex \
    "public docs must not treat verifier environment failure as attestation" \
    '(^|[^[:alnum:]_])environment failure[^.?!]{0,80}proves?[^.?!]{0,80}external attestation|failure bundle[^.?!]{0,80}proves?[^.?!]{0,80}key custody|failure report[^.?!]{0,80}proves?[^.?!]{0,80}live issuer status|failure report[^.?!]{0,80}proves?[^.?!]{0,80}production authority'

echo
printf "Results: %d/%d passed" "${PASS}" "${TOTAL}"
if [ "${FAIL}" -gt 0 ]; then
    printf " (%d FAILED)" "${FAIL}"
    echo
    exit 1
fi
echo " ✓"
