export const KERNEL_VERSION = "v4_formation_kernel_v1";
export const FIXTURE_NAMESPACE = "zlar_v4_formation_fixtures_v1";
export const SCHEMA_VERSION = "v1";
export const EVIDENCE_DOMAIN = "zlar:v4:evidence:v1";

export const PUBLIC_OPERATIONS = Object.freeze([
  "createKernel",
  "canonicalize",
  "identifyEvidence",
  "validateGraph",
  "evaluateTransition",
  "projectAuthorityView",
  "deriveClaims",
]);

export const REFUSAL_CODES = Object.freeze([
  "authority_expired",
  "authority_grant_missing",
  "authority_grant_unknown",
  "authority_revoked",
  "canonical_instant_invalid",
  "canonical_value_outside_grammar",
  "claim_ceiling_overreach",
  "claim_not_derivable",
  "credential_material_forbidden",
  "credential_promoted_to_authority",
  "derived_axis_input_forbidden",
  "derived_view_used_as_source",
  "destination_or_endpoint_forbidden",
  "effect_capability_forbidden",
  "effect_promoted_to_authority",
  "executable_reference_forbidden",
  "expired_frame_silent_use",
  "external_authority_reference_missing",
  "fixture_id_forbidden",
  "fixture_namespace_forbidden",
  "frame_lineage_conflict",
  "frame_lineage_not_current",
  "frame_presence_not_present",
  "freeform_institutional_value_forbidden",
  "fresh_eyes_inherited_input",
  "identity_mismatch",
  "identity_promoted_to_authority",
  "internal_contract_refusal",
  "lifecycle_fork",
  "live_mode_forbidden",
  "machine_judgment_forbidden",
  "non_synthetic_identifier",
  "per_action_step_missing",
  "person_score_forbidden",
  "positive_crossing_state_forbidden",
  "post_effect_retroactive_legitimacy",
  "profile_rule_missing",
  "proposal_identity_collision",
  "proposal_version_mismatch",
  "proxy_object_forbidden",
  "raw_json_text_ingress_forbidden",
  "real_authority_binding_forbidden",
  "real_effect_binding_forbidden",
  "record_type_unknown",
  "record_role_mismatch",
  "required_evidence_disputed",
  "required_evidence_missing",
  "reserved_matter_disposition_missing",
  "schema_version_unknown",
  "self_mandate_forbidden",
  "silent_proposition_fusion",
  "state_axis_collapsed",
  "synthetic_context_required",
  "transition_input_stale",
  "transition_not_allowed",
  "unknown_as_consent_or_permission",
  "unknown_binding_field",
  "v3_runtime_dependency_forbidden",
]);

export const RECORD_TYPES = Object.freeze([
  "attention_selection",
  "authority_domain_owner",
  "authoritative_head",
  "authority_profile",
  "challenge",
  "change_authority",
  "checkpoint",
  "closed_search",
  "consequence_observation",
  "constitutive_event",
  "constitutive_step",
  "credential_status",
  "exercise",
  "frame",
  "human_judgment_record",
  "interpretation",
  "lifecycle_snapshot",
  "mandate",
  "negative_evidence",
  "observation",
  "proposal",
  "recognition",
  "recovery_disposition",
  "recovery_observation",
  "recovery_request",
  "remedy_disposition",
  "remedy_request",
  "reserved_matter_disposition",
  "retroactive_legitimacy_attempt",
  "revocation",
  "revocation_authority",
  "revocation_milestone",
  "source_rule",
  "synthetic_transition_event",
]);

export const AUTHORITY_RECORD_TYPES = Object.freeze([
  "authority_domain_owner",
  "authoritative_head",
  "authority_profile",
  "change_authority",
  "constitutive_event",
  "constitutive_step",
  "exercise",
  "mandate",
  "recognition",
  "reserved_matter_disposition",
  "revocation",
  "revocation_authority",
  "revocation_milestone",
  "source_rule",
]);

export const DERIVED_RECORD_TYPES = Object.freeze([
  "authority_projection",
  "graph_validation",
  "proposition_assessment",
  "synthetic_assessment",
  "transition_receipt",
]);

export const CLAIM_TYPES = Object.freeze([
  "canonical_bytes_verified",
  "cross_object_invariants_evaluated",
  "evidence_identity_recomputed",
  "record_shape_validated",
  "synthetic_transition_accepted",
  "synthetic_transition_refused",
]);

export const CLOSED_LIMITATIONS = Object.freeze([
  "does_not_establish_current_authority",
  "does_not_establish_rightful_issuance",
  "does_not_establish_real_recognition",
  "does_not_establish_real_effect",
  "does_not_establish_lifecycle_closure",
  "does_not_establish_source_boundary_completion",
]);

export const FORBIDDEN_DERIVED_AXIS_KEYS = Object.freeze([
  "accepted",
  "authorized",
  "closed",
  "contest",
  "current",
  "effected",
  "executed",
  "freshness",
  "is_authorized",
  "lineage",
  "presence",
  "recognized",
  "revoked",
  "valid",
]);
